name: First github actions
on: [push]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node_modules
        run: npm install
      - name: Build the App
        run: npm run build
      - name: Build Finish
        run: echo "Build finishes!"

